version: "2"
services:
  postgres:
    image: circleci/postgres:12.4-postgis
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"